rubocop/rubocop-performance

lib/rubocop-performance.rb
lib/rubocop_performance/version.rb
rubocop-performance.gemspec

I broke this off from #1
I took as much as I could from
https://github.com/rubocop-hq/rubocop/blob/master/rubocop.gemspec
then changed the names and descriptions for rubocop-performance.
The gemspec expects LICENSE.txt to exist, so #2 should go in
first.

Create gemspec for initial version

---

lib/rubocop-performance.rb
lib/rubocop/performance/version.rb
lib/rubocop_performance/version.rb
rubocop-performance.gemspec

I seem to be confused about rspec-performance vs. rspec_performance.
Right now we have a mismatch between the require in the gemspec and the
version file, so the gem will not build. For now I'm going with the
dash, since it matches the name of the gem, but I'm not entirely
confident that is correct.
https://github.com/rubocop-hq/rubocop-performance/blob/c551accab8ce0710c6248163d7aeccb1819751ba/rubocop-performance.gemspec#L4

Fix directory file name

---

Rakefile

I was going to include RuboCop linting in this task, but RuboCop doesn't appear to be in a good state yet.

Create a default rake task

---

lib/rubocop-performance.rb
lib/rubocop/cop/performance/caller.rb
lib/rubocop/cop/performance/case_when_splat.rb
lib/rubocop/cop/performance/casecmp.rb
lib/rubocop/cop/performance/compare_with_block.rb
lib/rubocop/cop/performance/count.rb
lib/rubocop/cop/performance/detect.rb
lib/rubocop/cop/performance/double_start_end_with.rb
lib/rubocop/cop/performance/end_with.rb
lib/rubocop/cop/performance/fixed_size.rb
lib/rubocop/cop/performance/flat_map.rb
lib/rubocop/cop/performance/inefficient_hash_search.rb
lib/rubocop/cop/performance/lstrip_rstrip.rb
lib/rubocop/cop/performance/range_include.rb
lib/rubocop/cop/performance/redundant_block_call.rb
lib/rubocop/cop/performance/redundant_match.rb
lib/rubocop/cop/performance/redundant_merge.rb
lib/rubocop/cop/performance/redundant_sort_by.rb
lib/rubocop/cop/performance/regexp_match.rb
lib/rubocop/cop/performance/reverse_each.rb
lib/rubocop/cop/performance/sample.rb
lib/rubocop/cop/performance/size.rb
lib/rubocop/cop/performance/start_with.rb
lib/rubocop/cop/performance/string_replacement.rb
lib/rubocop/cop/performance/times_map.rb
lib/rubocop/cop/performance/unfreeze_string.rb
lib/rubocop/cop/performance/unneeded_sort.rb
lib/rubocop/cop/performance/uri_default_parser.rb
lib/rubocop/cop/performance_cops.rb

I copied over all the performance cops from RuboCop, including the
recent changes in https://github.com/rubocop-hq/rubocop/pull/6070
`rubocop/cop/performance_cops` matches `rubocop/cop/rspec_cops`: in [rubocop-rspec](https://github.com/rubocop-hq/rubocop-rspec/blob/master/lib/rubocop/cop/rspec_cops.rb)
I am open to suggestion about the call to `remove_const`. My thought was
that we would deprecate the performance cops maybe in rubocop version
0.58.0 or 0.59.0. Adding the rubocop-performance gem would be enough
to make those deprecation warnings go away. Then once rubocop 1.0.0 is
out for a bit we could do another release of rubocop-performance that
gets rid of the call to `remove_const`.

Import performance cops

---

.circleci/config.yml
.gitignore
Rakefile
rubocop-performance.gemspec
spec/spec_helper.rb

I based the circle config largely on the one from rubocop-rspec.
I removed the rubocop and documentation builds, since I haven't added
those rake tasks yet (I am working on documentation, and see #11 for
rubocop.) I also removed the Ruby 2.1 and 2.2 builds, since those
versions are no longer supported.
I went ahead and added the coverage rake task as well.
closes #10
NOTE: The tests will all fail until we get #13 in. It probably makes sense to merge that first, then rebase this and watch them pass. @bbatsov would it be possible to add this repo to circle when you have a chance?

Set up circleci

---

lib/rubocop/performance/version.rb

This release aims to reserve a gem name called rubocop-performance.

Preparing for 0.0.0 release

---

config/default.yml

This PR imports settings of default.yml related to Performance department from RuboCop Core.
Because all Performance cops are enabled, enabled.yml and disabled.yml are not imported.

Import Performance cop configs from RuboCop Core

---

lib/rubocop/cop/performance/casecmp.rb
spec/rubocop/cop/performance/casecmp_spec.rb

This PR imports rubocop-hq/rubocop#6156.
This PR changes offense message for `Performance/Casecmp` cop.
An example of an offense message change for the following code.
```console
% cat casecmp.rb
str.downcase == 'abc'
```
```console
% rubocop casecmp.rb --only Performance/Casecmp
C
Offenses:
casecmp.rb:1:5: C: Performance/Casecmp: Use casecmp instead of downcase
==.
str.downcase == 'abc'
^^^^^^^^^^^
1 file inspected, 1 offense detected
```
```console
% rubocop casecmp.rb --only Performance/Casecmp
C
Offenses:
casecmp.rb:1:1: C: Performance/Casecmp: Use str.casecmp('abc').zero?
instead of str.downcase == 'abc'.
str.downcase == 'abc'
^^^^^^^^^^^^^^^^^^^^^
```
This change makes it clear that users need to replace on the whole
including `zero?` method when …

Change offense message for `Performance/Casecmp`

---

rubocop-performance.gemspec

Fixes #22.
This PR specifies the same dependency version as rubocop-hq/rubocop-rspec#664.

[Fix #22] Change runtime dependency RuboCop to 0.58.0 or higher

---

.circleci/config.yml

This PR updates the following.
- Use CircleCI 2.1
- CI against Ruby 2.6 and trunk (2.7-dev)
- Drop Code Climate test-reporter
This change is synchronized with CirlceCI config of RuboCop Rails
https://github.com/rubocop-hq/rubocop-rails/blob/e57ad9cb6afd3807f9b3172405bbea7105ff4bac/config/default.yml
Also this PR aims at making CI successful first.
Code Climate test-reporter pends until #20 is resolved.

Update CircleCI Config

---

config/default.yml

This PR synchronizes config/default.yml with RuboCop Core.
https://github.com/rubocop-hq/rubocop/blob/04fb08d35556b4a620e5ee612ba8b19f30892d79/config/default.yml#L1969-L2200
Some missing cop configs and metadata are copied as is.

Synchronize config/default.yml with RuboCop Core

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

This PR adds .github template based on the ruboscop-hq/rubocop repository.
https://github.com/rubocop-hq/rubocop/tree/v0.65.0/.github

Add .github templates

---

Rakefile

The `rake new_cop` task was copied based on the following commit in the ruboscop-rspec.
https://github.com/rubocop-hq/rubocop-rspec/blob/v1.32.0/Rakefile#L65-L85

Add `rake new_cop` task

---

spec/project_spec.rb

Based on the following project spec added to RuboCop Rails.
https://github.com/rubocop-hq/rubocop-rails/commit/8641ef97c1387b03ecb300dfef38aab123c77067

Add project spec

---

CHANGELOG.md
lib/rubocop/performance/version.rb
rubocop-performance.gemspec

Several performance cops were moved to the style department in the RuboCop 0.67.
https://github.com/rubocop-hq/rubocop/releases/tag/v0.67.0
According to that, the next RuboCop Performance release requires RuboCop 0.67 or higher.
The next RuboCop Perfomance release removes some perfomance cops and bumps the dependent RuboCop version. So this PR makes the next release version to 1.1.0 instead of 1.0.1.

Preparing for 1.1.0 release

---

lib/rubocop/cop/performance/open_struct.rb

This PR suppresses the following warning.
```console
% path/to/rubocop-performance
% bundle exec rake
(snip)
/Users/koic/src/github.com/rubocop-hq/rubocop-performance/lib/rubocop/cop/performance/open_struct.rb:40:
warning: too many arguments for format string
```

Remove unused message format for `Performance/OpenStruct`

---

lib/rubocop/cop/performance/string_replacement.rb

This PR suppresses the following warning.
```console
/Users/koic/src/github.com/rubocop-hq/rubocop-performance/lib/rubocop/cop/performance/string_replacement.rb:89:
warning: deprecated Object#=~ is called on RuboCop::AST::Node; it always
returns nil
```
`Object#=~` has been deprecated from Ruby 2.6.
https://github.com/ruby/ruby/commit/ebff9dc10e6e72239c23e50acc7d3cbfdc659e7a
Related commit: https://github.com/ruby/ruby/commit/f7e94df0d66aff47745d189ab5a7858a92233d57

Suppress `Object#=~` deprecation warning

---

.rubocop.yml
Gemfile

Use edge RuboCop core for development
This PR uses edge RuboCop core for development. It is for RuboCop Performance to early catch change of RuboCop Core which is the runtime dependency gem.
And this PR suppresses the following warning by specifying rubocop-performance in .rubocop.yml
```console
% cd path/to/rubocop-performance
% bundle exec rake
bundle exec rubocop
Warning: unrecognized cop Performance/Caller found in .rubocop.yml
Inspecting 61 files
```

Use edge RuboCop for development

---

CHANGELOG.md
lib/rubocop/cop/performance/regexp_match.rb
rubocop-performance.gemspec

Follow up https://github.com/rubocop-hq/rubocop/pull/6965.
This PR fixes a false negartive for `Performance/RegexpMatch` when using RuboCop 0.68 or higher.
```ruby
def foo
if /re/.match(foo, 1)
do_something
end
end
```
RuboCop 0.67 warns.
```console
% rubocop _0.67.2_ --only Performance/RegexpMatch
C
Offenses:
example.rb:2:6: C: Performance/RegexpMatch: Use match? instead of match
when MatchData is not used.
if /re/.match(foo, 1)
^^^^^^^^^^^^^^^^^^
1 file inspected, 1 offense detected
```
RuboCop 0.68 does not warn. This is a false negative.
```console
% rubocop _0.68.1_ --only Performance/RegexpMatch --require
rubocop-performance
.
1 file inspected, no offenses detected
```
This PR fixes a false negative.
```console
% rubocop --only …
```

Fix a false negartive for `Performance/RegexpMatch`

---

mkdocs.yml
readthedocs.yml

This PR adds readthedocs.yml.
It is expected that the following homepage will be pushlished by this setting.
https://rubocop-performance.readthedocs.io/
Refer https://github.com/rubocop-hq/rubocop-performance/blob/v1.0.0/rubocop-performance.gemspec#L25.

Add readthedocs.yml

---

CHANGELOG.md
lib/rubocop/cop/performance/regexp_match.rb
spec/rubocop/cop/performance/regexp_match_spec.rb

This fixes false positives in `Performance/RegexpMatch` by only flagging single-argument `match` methods where either the receiver or the argument is a literal of type `Regexp`, `String`, `Symbol`.
Resolves https://github.com/rubocop-hq/rubocop-performance/issues/48

[Fix #48] Fix RegexpMatch false positive

---

CHANGELOG.md
lib/rubocop/cop/performance/fixed_size.rb
spec/rubocop/cop/performance/fixed_size_spec.rb

Fix `Performance/FixedSize` to accept const assign with some operation

---

rubocop-performance.gemspec

Follow up https://github.com/rubocop-hq/rubocop-rails/pull/59#issuecomment-495562071.
This PR updates metadata for gemspec.
The following URL is published and specified in gemspec.
https://docs.rubocop.org/projects/performance

Update metadata for gemspec

---

.rubocop_todo.yml
CHANGELOG.md
lib/rubocop/cop/performance/regexp_match.rb

Follow up https://github.com/rubocop-hq/rubocop/pull/7081.
This PR fixes a false negartive for `Performance/RegexpMatch` when using RuboCop 0.71 or higher.
This causes CI to fail.
https://circleci.com/gh/rubocop-hq/rubocop-performance/588
This is a regression similar to #47. This PR tries to fix it using a node pattern that has been used for a long time.

Fix a false negative for `Performance/RegexpMatch`

---

tasks/cops_documentation.rake

This PR prevents the following issue.
https://github.com/rubocop-hq/rubocop-performance/pull/58#issuecomment-493995756
Therefore this PR imports the following code from RuboCop core.
https://github.com/rubocop-hq/rubocop/blob/v0.71.0/tasks/cops_documentation.rake#L234-L246
Built-in Environment Variable `CI` by default `true` on CircleCI.
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

Assert manual synchronized for CI

---

.rubocop.yml
Rakefile

This PR fixes the following build error.
https://circleci.com/gh/rubocop-hq/rubocop-performance/623
Solve in the same way as RuboCop Rails.
https://github.com/rubocop-hq/rubocop-rails/pull/75

Fix a build error

---

lib/rubocop/cop/performance_cops.rb

Rails cops has been removed from RuboCop 0.72.
https://github.com/rubocop-hq/rubocop/releases/tag/v0.72.0
As a result of verification, the code to guard a warning is not necessary already.
Related PR ... https://github.com/rubocop-hq/rubocop-rails/pull/83

Remove unnecessary code to suppress warnings

---

CHANGELOG.md
lib/rubocop/cop/performance/redundant_merge.rb

Fixes #67.
This PR fixes an error for `Performance/RedundantMerge` when `MaxKeyValuePairs` option is set to `null`.
```yaml
require: rubocop-performance
Performance/RedundantMerge:
Enabled: true
MaxKeyValuePairs: null
```
```console
% bundle exec rubocop --only Performance/RedundantMerge -d
For /private/tmp/67: configuration from /private/tmp/67/.rubocop.yml
configuration from /Users/koic/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-performance-1.4.0/config/default.yml
configuration from /Users/koic/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-performance-1.4.0/config/default.yml
Default configuration from
/Users/koic/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.72.0/config/default.yml
Inspecting 2 files
Scanning /private/tmp/67/Gemfile
.Scanning …
```

[Fix #67] Fix an error for `Performance/RedundantMerge`

---

CHANGELOG.md
lib/rubocop/cop/performance/redundant_merge.rb
spec/rubocop/cop/performance/redundant_merge_spec.rb

Follow up https://github.com/rubocop-hq/rubocop-performance/pull/68#issuecomment-516072052.
#68 didn't solve an issue #67 with `Performance/RedundantMerge`.
This PR is corrected by adding a reproduction test.
Thanks @ashmaroli!

Fix an error for `Performance/RedundantMerge`

---

CHANGELOG.md
config/default.yml
lib/rubocop/cop/performance/count.rb
lib/rubocop/cop/performance/detect.rb
manual/cops_performance.md
spec/rubocop/cop/performance/count_spec.rb
spec/rubocop/cop/performance/detect_spec.rb

This is in response to #69. As noted in the issue, `SafeMode` has outlived its usefulness. Making use of being disabled by default or setting this as unsafe for auto-correction make more sense. 
I have left in the functionality that automatically disables these cops when the `Rails` cops are enabled. I'm not sure if that is functionality that we would like to maintain or not. These are the only 2 cops that function this way. If we remove the functionality, we can remove the `SafeMode` module from the core project.

Remove SafeMode from Count and Detect

---

CHANGELOG.md
lib/rubocop/cop/performance/flat_map.rb
spec/rubocop/cop/performance/flat_map_spec.rb

Fixes #70.
This PR fixes a false negative for `Performance/FlatMap` when using symbol to proc operator argument of `map` method.
@splattael I write your account both credit in the changelog. Thanks!

[Fix #70] Fix a false negative for `Performance/FlatMap`

---

Gemfile
relnotes/v1.0.0.md
relnotes/v1.1.0.md
relnotes/v1.2.0.md
relnotes/v1.3.0.md
relnotes/v1.4.0.md
relnotes/v1.4.1.md
relnotes/v1.5.0.md
tasks/cut_release.rake

This PR adds the following rake tasks.
```console
% rake -T | grep cut_release
rake cut_release:major                    # Cut a new major release,
create release notes and update documents
rake cut_release:minor                    # Cut a new minor release,
create release notes and update documents
rake cut_release:patch                    # Cut a new patch release,
create release notes and update documents
rake cut_release:pre                      # Cut a new pre release,
create release notes and update documents
```
And the release notes from v1.0.0 to v1.5.0 already released will be added.

Add release task and release notes

---

CHANGELOG.md
lib/rubocop/cop/performance/end_with.rb
lib/rubocop/cop/performance/start_with.rb
manual/cops_performance.md
spec/rubocop/cop/performance/end_with_spec.rb
spec/rubocop/cop/performance/start_with_spec.rb

Support for `String#match?` was added in https://github.com/rubocop-hq/rubocop/pull/5744, but not `Regexp#match?`.
Calling `=~` on a regex literal generates a specialised AST node, `match-with-lvasgn`, to support assigning named captures as local variables. The pattern would previously never match this usage.

Let Performance/StartWith and Performance/EndWith correct Regexp#match and Regexp#=~

---

Gemfile

This PR solves the following "The manual directory is out of sync" error when using Ruby 2.7.0-dev.
```console
% ruby -v
ruby 2.7.0dev (2019-12-03T05:51:14Z master e42d9d8df8) [x86_64-darwin17]
% CI=true bundle exec rake
(snip)
The manual directory is out of sync. Run `rake
generate_cops_documentation` and commit the results.
```
https://circleci.com/gh/rubocop-hq/rubocop-performance/869
This issue will be resolved with the release of YARD 0.9.21 or higher, which includes the following changes:
https://github.com/lsegal/yard/pull/1290

Workaround for broke CI with YARD 0.9.20 when using Ruby 2.7.0-dev

---

lib/rubocop/cop/performance/count.rb
manual/cops_performance.md

There's a bracket missing in the entry for the `Performance/Count` in the manual.

Add missing bracket for Count cop documentation

---

spec/project_spec.rb

This PR suppresses the following warning.
```console
% cd path/to/rubocop-performance
% bundle exec rake
(snip)
Running RuboCop...
spec/project_spec.rb: Metrics/LineLength has the wrong namespace -
should be Layout
```

Move `LineLength` cop from `Metrics` to `Layout` department

---

CHANGELOG.md
lib/rubocop/cop/performance/redundant_merge.rb
spec/rubocop/cop/performance/redundant_merge_spec.rb

Fixes #86.
This PR fixes the following incorrect autocorrect for `Performance/RedundantMerge` when using an empty hash argument.
```console
% cat example.rb
def something
hash.merge!({}) if blah?
hash
end
% rubocop --only Performance/RedundantMerge -a
E
Offenses:
example.rb:2:3: C: [Corrected] Performance/RedundantMerge: Use  instead
of hash.merge!({}).
hash.merge!({}) if blah?
^^^^^^^^^^^^^^^
example.rb:5:1: E: Lint/Syntax: unexpected token $end
(Using Ruby 2.6 parser; configure using TargetRubyVersion parameter,
under AllCops)
1 file inspected, 2 offenses detected, 1 offense corrected
% cat example.rb
def something
if blah?
hash
end
```
There is no good case code to replace an empty hash argument, so this PR changes it to not offense.
Before …

[Fix #86] Fix an incorrect autocorrect for `Performance/RedundantMerge`

---

CHANGELOG.md
config/default.yml
lib/rubocop/cop/performance/bind_call.rb
lib/rubocop/cop/performance_cops.rb
manual/cops.md
manual/cops_performance.md
spec/rubocop/cop/performance/bind_call_spec.rb

Fixes #77.
This PR adds new `Performance/BindCall` cop.
In Ruby 2.7, `UnboundMethod#bind_call` has been added.
- https://bugs.ruby-lang.org/issues/15955
- https://github.com/ruby/ruby/commit/83c6a1e
The `bind_call(obj, args, ...)` method is faster than `bind(obj).call(args, ...)`.
```console
% ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin17]
% gem i benchmark-ips
(snip)
% cat bench.rb
require 'benchmark/ips'
umethod = String.instance_method(:start_with?)
x.report('bind.call') { umethod.bind('hello, world').call('hello') }
x.report('bind_call') { umethod.bind_call('hello, world', 'hello') }
x.compare!
end
% ruby bench.rb
bind.call   122.167k i/100ms
bind_call   189.749k i/100ms
Calculating …
```

[Fix #77] Add new `Performance/BindCall` cop

---

rubocop-performance.gemspec

It suppresses the following warning.
```bash
$ bundle exec rake 
/home/pocke/ghq/github.com/rubocop-hq/rubocop-performance/rubocop-performance.gemspec:18: warning: global variable `$RS' not initialized
(snip)
```
The gemspec will use the null character separated string for file list instead of a newline.
I think it is more appropriate because a file path can contain a newline.
And `bundle gem`'s boilerplate also uses `-z` option.

Use `git ls-files -z` instead of splitting with newline

---

lib/rubocop/performance/inject.rb

Follow up of https://github.com/rubocop-hq/rubocop-extension-generator/pull/8.

Enable to work `Exclude` in AllCops section

---

CHANGELOG.md
config/default.yml
lib/rubocop/cop/performance/casecmp.rb
manual/cops_performance.md

Fixes #101.
`String#casecmp` and `String#casecmp?` behave differently when using Non-ASCII characters.
```console
'äöü'.casecmp('ÄÖÜ').zero? #=> false
'äöü'.casecmp?('ÄÖÜ')      #=> true
```
I thought about using a String literal encoding to prevent false positives. But, it is difficult to
static analyze the encoding of strings passed from outside.
As a result, this PR marks unsafe for `Performance/Casecmp` cop.

[Fix #101] Mark unsafe for `Performance/Casecmp` cop

---

CHANGELOG.md
lib/rubocop/cop/performance/reverse_each.rb
spec/rubocop/cop/performance/reverse_each_spec.rb

When reverse and each are on separate lines, we end up autocorrecting
```ruby
foo.reverse.
each { ... }
```
to
```ruby
foo.reverse_
each { ... }
```
. With this change, we will instead update to
```ruby
foo.reverse_each { ... }
```
cc: @joe-sharp @dischorde

Fixes multi-line ReverseEach autocorrection

---

CHANGELOG.md
lib/rubocop/cop/mixin/regexp_metacharacter.rb
lib/rubocop/cop/performance/delete_prefix.rb
lib/rubocop/cop/performance/delete_suffix.rb
lib/rubocop/cop/performance/end_with.rb
lib/rubocop/cop/performance/start_with.rb
lib/rubocop/cop/performance_cops.rb
manual/cops_performance.md
spec/rubocop/cop/performance/end_with_spec.rb
spec/rubocop/cop/performance/start_with_spec.rb

This PR supports regexp metacharacter `^` for `Performance/StartWith` cop and regexp metacharacter `$` for `Performance/EndWith` cop.

Support meta chars for `StartWith` and `EndWith` cops

---

CHANGELOG.md
lib/rubocop/cop/performance/regexp_match.rb
spec/rubocop/cop/performance/regexp_match_spec.rb

Fixes #55.
This PR fixes an incorrect autocorrect for `Performance/RegexpMatch` cop when using `str.=~(/regexp/)`.

[Fix #55] Fix an incorrect autocorrect for `Performance/RegexpMatch`

---

manual/cops_performance.md
tasks/cops_documentation.rake

Follow up to https://github.com/rubocop-hq/rubocop/pull/7947.

Add required Ruby version to generated cops manual

---

CHANGELOG.md
lib/rubocop/cop/performance/delete_prefix.rb
lib/rubocop/cop/performance/delete_suffix.rb

Fixes #111.
This PR fixes an error for `Performance/DeletePrefix` and `Performance/DeleteSuffix` cops when using autocorrection with RuboCop 0.81 or lower.

[Fix #111] Fix an error for `Performance/DeletePrefix` and `Performance/DeleteSuffix` cops

---

spec/rubocop/cop/performance/bind_call_spec.rb

This PR prepares for #112 and makes the `rake spec` successful with RuboCop 0.71, which is supported by RuboCop Performance 1.6.
This is a workaround until the CI is ready for RuboCop Performance 1.7.
RuboCop Performance 1.7 will drop some older RuboCop support versions.

Specify testing context of Ruby 2.7 for `Performance/BindCall`

---

CHANGELOG.md
lib/rubocop/cop/performance/delete_prefix.rb
lib/rubocop/cop/performance/delete_suffix.rb
manual/cops_performance.md
spec/rubocop/cop/performance/delete_prefix_spec.rb
spec/rubocop/cop/performance/delete_suffix_spec.rb

```ruby
str.sub(/suffix\z/, '')
str.sub!(/suffix\z/, '')
str.sub(/suffix$/, '')
str.sub!(/suffix$/, '')
str.delete_suffix('suffix')
str.delete_suffix!('suffix')
str.sub(/\Aprefix/, '')
str.sub!(/\Aprefix/, '')
str.sub(/^prefix/, '')
str.sub!(/^prefix/, '')
str.delete_prefix('prefix')
str.delete_prefix!('prefix')
```
Closes #115

[Fix #115] DeletePrefix and DeleteSuffix cops detects sub/sub! String methods

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/mixin/regexp_metacharacter.rb
lib/rubocop/cop/performance/delete_prefix.rb
lib/rubocop/cop/performance/delete_suffix.rb
lib/rubocop/cop/performance/end_with.rb
lib/rubocop/cop/performance/start_with.rb
spec/rubocop/cop/performance/delete_prefix_spec.rb
spec/rubocop/cop/performance/delete_suffix_spec.rb
spec/rubocop/cop/performance/end_with_spec.rb
spec/rubocop/cop/performance/start_with_spec.rb

Fixes #118.
Fix a false positive for `Performance/DeletePrefix`, `Performance/DeletePrefix`, `Performance/StartWith`, and `Performance/EndWith` cops when receiver is multiline string.

[Fix #118] Fix a false positive for `DeletePrefix` and `DeletePrefix` cops

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/range_include.rb
spec/rubocop/cop/performance/range_include_spec.rb

```ruby
('a'..'z').member?('b')  # => true
('a'..'z').cover?('b') # => true
```

Support `Range#member?` method for `Performance/RangeInclude` cop

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops.adoc
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/ancestors_include.rb
lib/rubocop/cop/performance_cops.rb
spec/rubocop/cop/performance/ancestors_include_spec.rb

Related link - https://github.com/JuanitoFatas/fast-ruby#ancestorsinclude-vs--code
```ruby
require 'bundler/inline'
gemfile(true) do
gem 'benchmark-ips'
gem 'benchmark-memory'
end
def fast
(Class <= Class)
(Class <= Module)
(Class <= Object)
(Class <= Kernel)
(Class <= BasicObject)
end
def slow
Class.ancestors.include?(Class)
Class.ancestors.include?(Module)
Class.ancestors.include?(Object)
Class.ancestors.include?(Kernel)
Class.ancestors.include?(BasicObject)
end
puts('********* IPS *********')
x.report('less than or equal') { fast }
x.report('ancestors.include?') { slow }
x.compare!
end
puts "********* MEMORY *********"
Benchmark.memory do |x|
x.report('less than or equal') { fast }
x.report('ancestors.include?') { slow }
x.compare!
end
```
```
********* IPS …
```

Add new `Performance/AncestorsInclude` cop

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops.adoc
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/big_decimal_with_numeric_argument.rb
lib/rubocop/cop/performance_cops.rb
spec/rubocop/cop/performance/big_decimal_with_numeric_argument_spec.rb

This is a simple one.
Related link - https://github.com/JuanitoFatas/fast-ruby/pull/172
I believe there is a better name for this cop.
It is faster to pass string argument to `BigDecimal` than numeric arguments.
```ruby
BigDecimal(1, 2)
BigDecimal(1.2, 3, exception: true)
BigDecimal('1', 2)
BigDecimal('1.2', 3, exception: true)
```
```ruby
require 'benchmark/ips'
require 'bigdecimal'
x.report("BigDecimal('1')")  { BigDecimal('1') }
x.report("BigDecimal(1)")    { BigDecimal(1) }
x.compare!
end
x.report("BigDecimal('1.0', 2)")  { BigDecimal('1.0', 2) }
x.report("BigDecimal(1.0, 2)")    { BigDecimal(1.0, 2) }
x.compare!
end
```
```
BigDecimal('1')   179.524k i/100ms
BigDecimal(1)   114.825k i/100ms …
```

Add new `Performance/BigDecimalWithNumericArgument` cop

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops.adoc
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/mixin/sort_block.rb
lib/rubocop/cop/performance/redundant_sort_block.rb
lib/rubocop/cop/performance_cops.rb
spec/rubocop/cop/performance/redundant_sort_block_spec.rb

Add new `Performance/RedundantSortBlock` cop

---

spec/rubocop/cop/performance/chain_array_allocation_spec.rb

This PR fixes the following build error.
```console
Failures:
1) RuboCop::Cop::Performance::ChainArrayAllocation Methods that
require an argument first
Failure/Error: expect(cop.messages.empty?).to be(false)
expected false
got true
`block (3 levels) in <top (required)>'
```
https://circleci.com/gh/rubocop-hq/rubocop-performance/1775
https://github.com/rubocop-hq/rubocop/pull/7868 has detected this wrong test case and this PR fixed it.

Fix a build error for `Performance/ChainArrayAllocation`

---

lib/rubocop/cop/performance/string_include.rb
spec/rubocop/cop/performance/string_include_spec.rb

This PR makes a safe detection for `Performance/StringInclude` cop when `match?` argument is a variable.
Symbol object does not have an `include?` method.
The following is an auto-corrected example code.
```console
% ruby -e ':symbol.include?(/pattern/)'
Traceback (most recent call last):
-e:1:in `<main>': undefined method `include?' for :symbol:Symbol (NoMethodError)
````
A variable possible to be a symbol object, so if `match?` argument is a variable, accept it.
As an unsafe option it might be possible to provide detection when argument is a variable.
First of all, this PR makes detection safe.
This PR haven't added a changelog entry as it is an unreleased feature.
and description in grammatically correct, …

Make a safe detection for `Performance/StringInclude`

---

docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/big_decimal_with_numeric_argument.rb

This PR adds the bad example in documentation for Performance/BigDecimalWithNumericArgument
Ref: [https://docs.rubocop.org/rubocop-performance/cops_performance.html#performancebigdecimalwithnumericargument](https://docs.rubocop.org/rubocop-performance/cops_performance.html#performancebigdecimalwithnumericargument)

Add bad example for BigDecimalWithNumericArgument

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc

We can't tell whether the receiver is a class or an object.
In my particular case, the false positive was for `Nokogiri::XML::Node#ancestors`:
https://github.com/sparklemotion/nokogiri/blob/v1.10.10/lib/nokogiri/xml/node.rb#L601

Mark Performance/AncestorsInclude as unsafe

---

CHANGELOG.md
lib/rubocop/cop/performance/ancestors_include.rb
spec/rubocop/cop/performance/ancestors_include_spec.rb

Fixes #147.
This PR fixes an error for `Performance/AncestorsInclude` when using `ancestors.include?` without receiver.

[Fix #147] Fix an error for `Performance/AncestorsInclude`

---

CHANGELOG.md
lib/rubocop/cop/performance/big_decimal_with_numeric_argument.rb
spec/rubocop/cop/performance/big_decimal_with_numeric_argument_spec.rb

The precision argument to `BigDecimal()` is ignored unless the value is a float or rational. Converting the value from a float to a string when a precision is specified changes the result.
$ ruby -rbigdecimal -e "puts BigDecimal(3.14, 1)"
0.3e1
$ ruby -rbigdecimal -e "puts BigDecimal('3.14', 1)"
0.314e1

Don't autocorrect BigDecimal with float when precision is specified

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/string_include.rb

Fixes #145.
This PR marks `Performance/StringInclude` as `SafeAutocorrect: false` and disable autocorrect by default. The cop's offenses are not safe to auto-correct if a receiver is nil.

[Fix #145] Mark `Performance/StringInclude` as unsafe

---

CHANGELOG.md
rubocop-performance.gemspec
spec/rubocop/cop/performance/casecmp_spec.rb
spec/rubocop/cop/performance/chain_array_allocation_spec.rb
spec/rubocop/cop/performance/compare_with_block_spec.rb
spec/rubocop/cop/performance/count_spec.rb
spec/rubocop/cop/performance/detect_spec.rb
spec/rubocop/cop/performance/double_start_end_with_spec.rb
spec/rubocop/cop/performance/end_with_spec.rb
spec/rubocop/cop/performance/fixed_size_spec.rb
spec/rubocop/cop/performance/flat_map_spec.rb
spec/rubocop/cop/performance/regexp_match_spec.rb
spec/rubocop/cop/performance/start_with_spec.rb
spec/rubocop/cop/performance/string_include_spec.rb
spec/rubocop/cop/performance/string_replacement_spec.rb
spec/rubocop/cop/performance/sum_spec.rb
spec/rubocop/cop/performance/times_map_spec.rb

This PR uses new `expect_offense`, `expect_correction` instead of `cop.offenses`, `cop.highlights`, and `cop.messages` APIs.
Therefore, RuboCop Performance requires Rails 0.87 or higher.

Use new `expect_offense`, `expect_correction` instead of old APIs

---

CHANGELOG.md
lib/rubocop/cop/performance/ancestors_include.rb
spec/rubocop/cop/performance/ancestors_include_spec.rb

Fixes #159.
This PR fixes a false positive for `Performance/AncestorsInclude` when receiver is a variable.
As the cop's example shows, this change mainly targets when the receiver is a constant. It can cause false negatives, but it may be less than false positives.
And this change may lead to removing unsafe marked by #149.

[Fix #159] Fix a false positive for `Performance/AncestorsInclude`

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/count.rb
lib/rubocop/cop/performance/detect.rb
spec/rubocop/cop/performance/count_spec.rb
spec/rubocop/cop/performance/detect_spec.rb

Closes #63 
I have rechecked existing `Detect` and `Count` cops - they are handling almost everything that is needed/requested (as mentioned in https://github.com/rubocop-hq/rubocop-performance/issues/63#issuecomment-512884529). 
So implemented checks for 2 missing methods in this PR.

Extend `Performance/Detect` cop with check for `filter` method and `Performance/Count` cop with checks for `find_all` and `filter` methods

---

CHANGELOG.md
lib/rubocop/cop/performance/collection_literal_in_loop.rb
spec/rubocop/cop/performance/collection_literal_in_loop_spec.rb

The test added here demonstrates the problem:
```ruby
$ bundle exec rspec spec/rubocop/cop/performance/collection_literal_in_loop_spec.rb:149
Run options: include {:locations=>{"./spec/rubocop/cop/performance/collection_literal_in_loop_spec.rb"=>[149]}}
Randomized with seed 21526
RuboCop::Cop::Performance::CollectionLiteralInLoop
when inside one of `Enumerable` loop-like methods
registers an offense when the method is called with no receiver (FAILED - 1)
Failures:
1) RuboCop::Cop::Performance::CollectionLiteralInLoop when inside one of `Enumerable` loop-like methods registers an offense when the method is called with no receiver
Failure/Error: receiver != node && !receiver.descendants.include?(node)
NoMethodError:
undefined method `descendants' for nil:NilClass
Finished in 0.03141 seconds …
```

Handle Enumerable methods called with no receiver in CollectionLiteralInLoop

---

CHANGELOG.md
lib/rubocop/cop/performance/sum.rb
spec/rubocop/cop/performance/sum_spec.rb

Fixes #165.
This PR fixes a false positive for `Performance/Sum` when using initial value argument is a variable.

[Fix #165] Fix a false positive for `Performance/Sum`

---

CHANGELOG.md
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/detect.rb
rubocop-performance.gemspec
spec/rubocop/cop/performance/detect_spec.rb

`[1, 2, 3].detect{ ... }[0]` and `[1, 2, 3].detect{ ... }[-1]` will now be caught and corrected by the cop as if they were `first` and `last`.
Fixes #163.

[Fix #163] Detect array indexes for `Performance/Detect`

---

CHANGELOG.md
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/sum.rb
spec/rubocop/cop/performance/sum_spec.rb

Followup to https://github.com/rubocop-hq/rubocop-performance/pull/137.
`inject(&:+)` is another slower way to write `sum`.

Handle inject(&:+) in Performance/Sum

---

CHANGELOG.md
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/sum.rb
spec/rubocop/cop/performance/sum_spec.rb

Followup to https://github.com/rubocop-hq/rubocop-performance/pull/137.
Passing the block directly to `sum` is faster, and avoids allocating an intermediate array.
```ruby
require 'bundler/inline'
gemfile(true) do
gem 'benchmark-ips'
gem 'benchmark-memory'
end
SCENARIOS = [
1..10,
1..1_000,
1..100_000
]
SCENARIOS.each do |range|
puts
puts " #{range.inspect} ".center(80, "=")
puts
x.report("map { |n| n ** 2 }.sum") { range.map { |n| n ** 2 }.sum }
x.report("sum { |n| n ** 2 }")     { range.sum { |n| n ** 2 } }
x.compare!
end
Benchmark.memory do |x|
x.report("map { |n| n ** 2 }.sum") { range.map { |n| n ** 2 }.sum }
x.report("sum { |n| n ** 2 }")     { range.sum { |n| n ** 2 } }
x.compare!
end
end
```
```
==================================== 1..10 …
```

Handle map { ... }.sum in Performance/Sum

---

docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/sum.rb
spec/rubocop/cop/performance/sum_spec.rb

See https://github.com/rubocop-hq/rubocop-performance/pull/170#issuecomment-696166317.
When `map` is passed a block argument and `sum` is passed an initial value, they need to be combined in the new `sum` call's argument list.
I don't think a changelog entry is necessary since this correction hasn't been released yet.

Fix an incorrect autocorrect for Performance/Sum

---

CHANGELOG.md
lib/rubocop/cop/performance/sum.rb
spec/rubocop/cop/performance/sum_spec.rb

Fixes https://github.com/rubocop-hq/rubocop-performance/issues/177
Doesn't fully resolve the issue, since it only works on array literals. But this removes at least one false positive.

`Performance/Sum` should avoid, or warn about, empty arrays

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc

As noted [here](https://github.com/rubocop-hq/rubocop-performance/pull/140#discussion_r487437198).

`Performance/CollectionLiteralInLoop` should be `Enabled: 'pending'`

---

docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/detect.rb

Correct double named `find_all` to `find_all` and `filter` introduced by 382340966b7b065fe463680c73cb56ab4b0ab878.

Fix typo introduced by #167

---

lib/rubocop/cop/performance/redundant_block_call.rb

Follow https://github.com/rubocop-hq/rubocop/pull/8955#issuecomment-717604989
This PR suppresses the following `Lint/ToEnumArguments` offense.
```console
% cd path/to/rubocop-performance
% bundle exec rake
(snip)
Offenses:
lib/rubocop/cop/performance/redundant_block_call.rb:83:19: W:
Lint/ToEnumArguments: Ensure you correctly provided all the arguments.
calls = to_enum(:blockarg_calls, body, argname)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
96 files inspected, 1 offense detected
RuboCop failed!
```
Thank you for the improving suggestion @marcandre!

Suppress `Lint/ToEnumArguments`'s offense

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops.adoc
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/array_semi_infinite_range_slice.rb
lib/rubocop/cop/performance_cops.rb
spec/rubocop/cop/performance/array_semi_infinite_range_slice_spec.rb

Inspired by https://github.com/JuanitoFatas/fast-ruby/pull/181
```ruby
require 'bundler/inline'
gemfile(true) do
gem 'benchmark-ips'
end
ARRAY = (1..100).to_a
x.report('Array#take(3)')   { ARRAY.take(3) }
x.report('Array#[..2]')     { ARRAY[..2] }
x.compare!
end
x.report('Array#drop(90)')  { ARRAY.drop(90) }
x.report('Array#[90..]')    { ARRAY[90..] }
x.compare!
end
```
```
Array#take(3)   836.792k i/100ms
Array#[..2]   491.866k i/100ms
Calculating -------------------------------------
Array#take(3)      8.578M (± 1.2%) i/s -     43.513M in   5.073484s
Array#[..2]      4.961M (± 1.1%) i/s -     25.085M in   5.056928s
Comparison:
Array#take(3):  8577744.5 i/s
Array#[..2]:  4961147.7 i/s - 1.73x  (± …
```

Add new `Performance/ArraySemiInfiniteRangeSlice` cop

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/caller.rb
spec/rubocop/cop/performance/caller_spec.rb

This PR supports auto-correction for `Performance/Caller`.

Support auto-correction for `Performance/Caller`

---

CHANGELOG.md
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/sum.rb
spec/rubocop/cop/performance/sum_spec.rb

Fixes #171.
This PR makes `Performance/Sum` cop can be changed auto-correction scope depending on the value of `SafeAutoCorrect` in .rubocop.yml.
Its auto-correction is marked as safe by default (`SafeAutoCorrect: true`) to prevent `TypeError` in auto-correced code when initial value is not specified as shown below:
```ruby
['a', 'b'].sum # => (String can't be coerced into Integer)
```
Therefore if initial value is not specify as in that code, it will not be auto-corrected.
If user always want to enable auto-correction, user can set `SafeAutoCorrect: false`.
```yaml
Performance/Sum:
SafeAutoCorrect: false
```
`SafeAutoCorrect` remains `true` by default, so the behavior does not change.
and description in …

[Fix #171] Extend auto-correction support for `Performance/Sum`

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/unfreeze_string.rb
spec/rubocop/cop/performance/unfreeze_string_spec.rb

This PR supports autocorrect for `Performance/UnfreezeString`.

Support autocorrect for `Performance/UnfreezeString`

---

CHANGELOG.md
lib/rubocop/cop/performance/chain_array_allocation.rb
spec/rubocop/cop/performance/chain_array_allocation_spec.rb

Closes #185
The real change is this line - https://github.com/rubocop-hq/rubocop-performance/pull/196/files#diff-aadc09c37851b4bcdde6d9af4f194ba5bd2578117e64170d87d2174e17772a63R52
Other changes are a small refactoring rewriting a patterns with `%CONST` feature.
cc @marcandre

Fix incorrect replacement recommendation for `Performance/ChainArrayAllocation`

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/array_semi_infinite_range_slice.rb

This cop is unsafe for string slices because string does not have `#take` and `#drop` methods. Although we could change the cop to skip literal strings, it still remains unsafe for variables which we cannot determine statically if they are arrays or strings.
Closes #197, #198 

[Fix #197] Disable `Performance/ArraySemiInfiniteRangeSlice` cop

---

CHANGELOG.md
lib/rubocop/cop/performance/reverse_each.rb
spec/rubocop/cop/performance/reverse_each_spec.rb

Fixes https://github.com/testdouble/standard/issues/230.
This PR fixes the following incorrect auto-correct for `Performance/ReverseEach` when using multi-line `reverse.each` with leading dot.
```ruby
% cat example.rb
[1, 2, 3]
.reverse
.each do |idx|
puts idx
end
```
```console
% bundle exec rubocop -a --only Performance/ReverseEach
% cat example.rb
[1, 2, 3]
.reverse
_each do |idx|
puts idx
end
```
```console
% bundle exec rubocop -a --only Performance/ReverseEach
% cat example.rb
[1, 2, 3]
.reverse_each do |idx|
puts idx
end
```

Fix an incorrect auto-correct for `Performance/ReverseEach`

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/constant_regexp.rb
spec/rubocop/cop/performance/constant_regexp_spec.rb

[Fix #205] Update `Performance/ConstantRegexp` to allow memoized regexps

---

CHANGELOG.md
lib/rubocop/cop/performance/sum.rb
spec/rubocop/cop/performance/sum_spec.rb

Fixes #207.
This PR fixes an error for `Performance/Sum` when using `map(&do_something).sum` without receiver.

[Fix #207] Fix an error for `Performance/Sum`

---

lib/rubocop/cop/performance/redundant_split_regexp_argument.rb
spec/rubocop/cop/performance/redundant_split_regexp_argument_spec.rb

Follow #190.
This PR fixes the following incorrect auto-correct for `Performance/RedundantSplitRegexpArgument` when using consecutive special string chars.
```console
% cat example.rb
"foo\nbar\nbaz\n".split(/\n\n/)
% bundle exec rubocop example.rb --only Performance/RedundantSplitRegexpArgument -a
C
Offenses:
example.rb:1:25: C: [Corrected]
Performance/RedundantSplitRegexpArgument: Use string as argument instead of regexp.
"foo\nbar\nbaz\n".split(/\n\n/)
^^^^^^
1 file inspected, 1 offense detected, 1 offense corrected
```console
% cat example.rb
"foo\nbar\nbaz\n".split("nn")
```
```console
% cat example.rb
"foo\nbar\nbaz\n".split("\n\n")
```
and description in grammatically correct, complete …
```

Fix an incorrect auto-correct for `Performance/RedundantSplitRegexpArgument`

---

CHANGELOG.md
lib/rubocop/cop/performance/bind_call.rb
spec/rubocop/cop/performance/bind_call_spec.rb

This PR fix a false negative for `Performance/BindCall`
when receiver is not a method call.
I heard that it could not be detected by the following changes in rails/rails.
https://github.com/rails/rails/commit/6515d6985d2b537486bd9d1faa95212a508dc42c
Thanks @kamipo.

Fix a false negative for `Performance/BindCall`

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc

This PR enables auto-correct for `Performance/StartWith` and `Performance/EndWith` cops.
These cops are expected to be performed as unsafe auto-correction by default.
Thanks for the feedback @amatsuda!

Enable auto-correct for `Performance/StartWith` and `Performance/EndWith` cops

---

CHANGELOG.md
lib/rubocop/cop/performance/redundant_equality_comparison_block.rb
spec/rubocop/cop/performance/redundant_equality_comparison_block_spec.rb

Fixes #214.
This PR fixes a false positive for `Performance/RedundantEqualityComparisonBlock` when using multiple block arguments.

[Fix #214] Fix a false positive for `Performance/RedundantEqualityComparisonBlock`

---

CHANGELOG.md
lib/rubocop/cop/performance/redundant_split_regexp_argument.rb
spec/rubocop/cop/performance/redundant_split_regexp_argument_spec.rb

Fixes #216.
This PR fixes a false positive for `Performance/RedundantSplitRegexpArgument` when using split method with ignore case regexp option.

[Fix #216] Fix a false positive for `Performance/RedundantSplitRegexpArgument`

---

CHANGELOG.md
lib/rubocop/cop/performance/redundant_equality_comparison_block.rb
spec/rubocop/cop/performance/redundant_equality_comparison_block_spec.rb

Fixes #217.
This PR fixes a false positive for `Performance/RedundantEqualityComparisonBlock` when using block argument is used for an argument of `is_a`.

[Fix #217] Fix a false positive for `Performance/RedundantEqualityComparisonBlock`

---

CHANGELOG.md
lib/rubocop/cop/performance/redundant_block_call.rb
spec/rubocop/cop/performance/redundant_block_call_spec.rb

Fixes #162.
This PR fixes a false positive for `Performance/RedundantBlockCall` when an optional block that is overridden by block variable.

[Fix #162] Fix a false positive for `Performance/RedundantBlockCall`

---

CHANGELOG.md
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/reverse_each.rb
spec/rubocop/cop/performance/reverse_each_spec.rb

Fixes #36.
This PR fixes a false positive for `Performance/ReverseEach` when `each` is called on `reverse` and using the result value.

[Fix #36] Fix a false positive for `Performance/ReverseEach`

---

CHANGELOG.md
lib/rubocop/cop/performance/redundant_equality_comparison_block.rb
spec/rubocop/cop/performance/redundant_equality_comparison_block_spec.rb

This PR fixes a false positive for `Style/RedundantEqualityComparisonBlock` when using one argument with comma separator in block argument.

Fix a false positive for `Style/RedundantEqualityComparisonBlock`

---

CHANGELOG.md
lib/rubocop/cop/performance/redundant_equality_comparison_block.rb
spec/rubocop/cop/performance/redundant_equality_comparison_block_spec.rb

Fixes #225
This PR fixes a false positive for `Style/RedundantEqualityComparisonBlock` when using `any?` with `===` comparison block and block argument is not used as a receiver for `===`.

[Fix #225] Fix a false positive for `Style/RedundantEqualityComparisonBlock`

---

CHANGELOG.md
lib/rubocop/cop/performance/redundant_split_regexp_argument.rb
spec/rubocop/cop/performance/redundant_split_regexp_argument_spec.rb

Fixes #222.
This PR fixes a false positive for `Performance/RedundantSplitRegexpArgument` when `split` method argument is exactly one spece regexp `/ /`.

[Fix #222] Fix a false positive for `Performance/RedundantSplitRegexpArgument`

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/redundant_merge.rb

As per https://twitter.com/bbatsov/status/1376631309020315654
`Performance/RedundantMerge` makes the following autocorrection:
```diff
-    @operation_builder.merge!(foobar: [{name: "passed_option"}])
+    @operation_builder[:foobar] = [{name: "passed_option"}]
```
But if `@operation_builder` here is not a hash, this is a bad correction, thus making the cop unsafe.

Mark `Performance/RedundantMerge` as unsafe

---

.circleci/config.yml
.rubocop.yml
CHANGELOG.md
rubocop-performance.gemspec
spec/rubocop/cop/performance/delete_prefix_spec.rb
spec/rubocop/cop/performance/delete_suffix_spec.rb
spec/rubocop/cop/performance/redundant_equality_comparison_block_spec.rb
tasks/cops_documentation.rake

Follow https://github.com/rubocop/rubocop/pull/9648.

Drop Ruby 2.4 support

---

CHANGELOG.md
config/obsoletion.yml
lib/rubocop/performance.rb
rubocop-performance.gemspec
spec/project_spec.rb

Follow https://github.com/rubocop-hq/rubocop/pull/9206 and https://github.com/rubocop-hq/rubocop/pull/9143.
This PR requires RuboCop 1.7 or higher due to support obsoletion configuration and reverts https://github.com/rubocop/rubocop-performance/commit/0e59891.

Require RuboCop 1.7 or higher due to support obsoletion configuration

---

CHANGELOG.md
lib/rubocop/cop/performance/map_compact.rb
spec/rubocop/cop/performance/map_compact_spec.rb

Fixes #236.
This PR fix an incorrect auto-correct for `Performance/MapCompact` when using multi-line leading dot method calls.

[Fix #236] Fix an incorrect auto-correct for `Performance/MapCompact`

---

CHANGELOG.md
lib/rubocop/cop/performance/map_compact.rb
spec/rubocop/cop/performance/map_compact_spec.rb

Fixes #238.
This PR fixes an incorrect auto-correct for `Performance/MapCompact` when invoking a method after `map { ... }.compact` on the same line.

[Fix #238] Fix an incorrect auto-correct for `Performance/MapCompact`

---

CHANGELOG.md
lib/rubocop/cop/performance/map_compact.rb
spec/rubocop/cop/performance/map_compact_spec.rb

Fixes #242.
This PR fixes an error for `Performance/MapCompact` when using multiline `map { ... }.compact` and assigning to return value.

[Fix #242] Fix an error for `Performance/MapCompact`

---

docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/map_compact.rb
spec/rubocop/cop/performance/map_compact_spec.rb

Follow https://github.com/rails/rails/pull/42090#discussion_r621864689
This PR adds an example to the doc (and test) that `compact.map` and `filter_map` are not same.

Update the doc for `Performance/MapCompact`

---

CHANGELOG.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/delete_prefix.rb
lib/rubocop/cop/performance/delete_suffix.rb

Fixes #245.
This PR marks `Performance/DeletePrefix` and `Performance/DeleteSuffix` as unsafe.

[Fix #245] Mark `Performance/DeletePrefix` and `Performance/DeleteSuffix` as unsafe

---

CHANGELOG.md
lib/rubocop/cop/performance/map_compact.rb
spec/rubocop/cop/performance/map_compact_spec.rb

Fixes #247.
This PR fixes an incorrect auto-correct for `Performance/MapCompact` when using multi-line trailing dot method calls.

[Fix #247] Fix an incorrect auto-correct for `Performance/MapCompact`

---

CHANGELOG.md
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/redundant_string_chars.rb
spec/rubocop/cop/performance/redundant_string_chars_spec.rb

Fixes #249.
This PR fixes a false positive for `Performance/RedundantStringChars` when using `str.chars.last` and `str.chars.drop`.

[Fix #249] Fix a false positive for `Performance/RedundantStringChars`

---

CHANGELOG.md
lib/rubocop/cop/performance/unfreeze_string.rb
spec/rubocop/cop/performance/unfreeze_string_spec.rb

Fixes #252.
This PR fixes an incorrect auto-correct for `Performance/UnfreezeString` when invoking a method after `String.new` with a string.

[Fix #252] Fix an incorrect auto-correct for `Performance/UnfreezeString`

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
Rakefile
spec/project_spec.rb
tasks/changelog.rake
tasks/changelog.rb
tasks/cut_release.rake

Follow https://github.com/rubocop/rubocop/pull/8930 and https://github.com/rubocop/rubocop/commit/3fc75c4

Add rake tasks for alternative way to specify Changelog entries

---

CHANGELOG.md
lib/rubocop/cop/performance/redundant_equality_comparison_block.rb
spec/rubocop/cop/performance/redundant_equality_comparison_block_spec.rb

Fixes #255.
This PR fixes a false positive for `Performance/RedundantEqualityComparisonBlock` when using block argument is used for an argument of operand.

[Fix #255] Fix a false positive for `Performance/RedundantEqualityComparisonBlock`

---

CHANGELOG.md
lib/rubocop/cop/performance/map_compact.rb
spec/rubocop/cop/performance/map_compact_spec.rb

Fixes #257.
This PR fixes an incorrect auto-correct for `Performance/MapCompact` when using multi-line `collection.map { ... }.compact` as a method argument.

[Fix #257] Fix an incorrect auto-correct for `Performance/MapCompact`

---

changelog/change_unmark_autocorrect_false_from_performance_string_include.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc

This `AutoCorrect: false` looks like it was set when there was no way to safe autocorrect by `SafeAutocorrect: false`.
Test code for the autocorrection exists. So it can be enabled by default. However, it is still unsafe because `SafeAutocorrect: false`.

Unmark `AutoCorrect: false` from `Performance/StringInclude`

---

rubocop-performance.gemspec

Follows rubocop/rubocop#10239. Update gemspec to require MFA for privileged operations.

Set `rubygems_mfa_required` in gemspec.

---

CHANGELOG.md
changelog/new_add_performancesum_option_to_ignore.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/sum.rb
spec/rubocop/cop/performance/sum_spec.rb

Some codebases may contain non-numeric classes which implement a `:+` method.
If `a`, `b` and `c` are objects of such a class, then certain corrections
do not apply:
```ruby
[a, b].reduce(c, :+) # is equivalent to
[a, b].sum(c)
[a, b].map(&:to_i).sum # is equivalent to
[a, b].sum(&:to_i)
[a, b].reduce(:+) # works
[a, b].sum # raises TypeError
```
For users who wish to only register offenses where auto-correction
is unproblematic, we add the option `OnlySumOrWithInitialValue`
to the `Performance/Sum` cop.
The option is disabled by default, so standard behavior is preserved,
and can be activated by setting `OnlySumOrWithInitialValue: true`.
[1]: …

[Fix #204] Add `Performance/Sum` option to ignore potential false positives

---

changelog/change_mark_performancesum_autocorrection_as.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/sum.rb
spec/rubocop/cop/performance/sum_spec.rb

The documentaion of `Performance/Sum` talked about setting
`SafeAutoCorrect: true` for the cop, but Rubocop complained:
```
Warning: Performance/Sum does not support SafeAutoCorrect parameter.
Supported parameters are:
- Enabled
```
so we add the `SafeAutoCorrect` option to the cop's defaults
and thereby mark it as (partially) unsafe.
This is NOT a change in behavior: The cop will still perform all
safe auto-corrections when using `-a`, and also (by default)
perform all unsafe auto-corrections when using `-A`.
Furthermore we extend the documentation in order to make it even more
clear in _which_ cases auto-correction is unsafe, and _why_.
[1]: …

Mark `Performance/Sum` auto-correction as unsafe and extend documentation

---

changelog/new_add_to_d_to_BigDecimalWithNumericArgument.md
config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc
lib/rubocop/cop/performance/big_decimal_with_numeric_argument.rb
spec/rubocop/cop/performance/big_decimal_with_numeric_argument_spec.rb

The [`bigdecimal/util`](https://github.com/ruby/bigdecimal/blob/v3.0.2/lib/bigdecimal/util.rb) library adds `#to_d` to several numeric types, where
```ruby
numeric.to_d(*args)
```
is equivalent to
```ruby
BigDecimal(numeric, *args)
```
and the performance improvement of `BigDecimalWithNumericArgument`
therefore equally applies here.
Also, the exception of `Float` with specified precision does not seem
to make sense and is therefore dropped:
```
BigDecimal("1.2")   266.340k i/100ms
BigDecimal("1.2", 9)   261.542k i/100ms
BigDecimal(1.2, 9)    44.366k i/100ms
1.2.to_d    42.809k i/100ms
1.2.to_d(9)    43.915k i/100ms
Calculating -------------------------------------
BigDecimal("1.2")      2.634M (± 1.8%) i/s -     13.317M in   5.056712s …
```

Add #to_d support to BigDecimalWithNumericArgument

---

changelog/change_unmark_autocorrect_false_from_performance_case_when_splat.md
config/default.yml

Follow up to https://github.com/rubocop/rubocop/pull/6177.
This `AutoCorrect: false` looks like it was set when there was no way to safe autocorrect by `SafeAutocorrect: false`.

Change from `AutoCorrect: false` to `SafeAutoCorrect: false` for  `Performance/CaseWhenSplat`

---

config/default.yml

Follow up to https://github.com/rubocop/rubocop/pull/6177.
This `AutoCorrect: false` looks like it was set when there was no way to safe autocorrect by `SafeAutocorrect: false`.

Change from `AutoCorrect: false` to `SafeAutoCorrect: false` for  `Performance/TimesMap`

---

changelog/fix_incorrect_autocorrect_for_performance_map_compact.md
lib/rubocop/cop/performance/map_compact.rb
spec/rubocop/cop/performance/map_compact_spec.rb

This PR fixes an incorrect autocorrect for `Performance/MapCompact` when using `map.compact.first` and there is a line break after `map.compact` and receiver.

Fix an incorrect autocorrect for `Performance/MapCompact`

---

changelog/fix_false_positive_for_performance_string_identifier_argument.md
lib/rubocop/cop/performance/string_identifier_argument.rb
spec/rubocop/cop/performance/string_identifier_argument_spec.rb

Fixes #278.
This PR fixes a false positive for `Performance/StringIdentifierArgument` when using `attr`. `attr` may not be used because `Style/Attr` registers an offense.

[Fix #278] Fix a false positive for `Performance/StringIdentifierArgument`

---

changelog/fix_an_error_for_performance_block_given_with_explicit_block.md
lib/rubocop/cop/performance/block_given_with_explicit_block.rb
spec/rubocop/cop/performance/block_given_with_explicit_block_spec.rb

Fixes #281.
This PR fixes an error for `Performance/BlockGivenWithExplicitBlock` when using Ruby 3.1's anonymous block forwarding.

[Fix #281] Fix an error for `Performance/BlockGivenWithExplicitBlock`

---

CHANGELOG.md
changelog/fix_fix_error_for_performance_mapcorrect_when_line_break.md
lib/rubocop/cop/performance/map_compact.rb
spec/rubocop/cop/performance/map_compact_spec.rb

This fixes an issue where code like the following would cause an error in the `Performance/MapCompact` cop:
```ruby
collection
.map(&:do_something).compact
.first
```
The following error was outcome:
```
An error occurred while Performance/MapCompact cop was inspecting /home/ydah/sandbox/test.rb:1:0.
Parser::Source::TreeRewriter detected clobbering
/home/ydah/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/parser-3.1.1.0/lib/parser/source/tree_rewriter.rb:427:in `trigger_policy'
/home/ydah/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/parser-3.1.1.0/lib/parser/source/tree_rewriter.rb:414:in `enforce_policy'
/home/ydah/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/parser-3.1.1.0/lib/parser/source/tree_rewriter/action.rb:233:in `call' …
```

Fix an error for `Performance/MapCompact` when using `map(&:do_something).compact.first` and there is a line break after `map.compact` and receiver

---

.circleci/config.yml
.rubocop.yml
changelog/change_drop_ruby_2_5_support.md
lib/rubocop/cop/mixin/regexp_metacharacter.rb
lib/rubocop/cop/performance/case_when_splat.rb
rubocop-performance.gemspec

Follow up https://github.com/rubocop/rubocop/pull/10577.

Drop Ruby 2.5 support

---

changelog/fix_recover_ruby_24_analysis.md
lib/rubocop/cop/performance/delete_prefix.rb
lib/rubocop/cop/performance/delete_suffix.rb
lib/rubocop/cop/performance/redundant_equality_comparison_block.rb
spec/rubocop/cop/performance/delete_prefix_spec.rb
spec/rubocop/cop/performance/delete_suffix_spec.rb
spec/rubocop/cop/performance/redundant_equality_comparison_block_spec.rb

Follow up https://github.com/rubocop/rubocop/pull/10632.
Reverts #232 and https://github.com/rubocop/rubocop-performance/commit/e3c374b.

Recover Ruby 2.4 code analysis using `TargetRubyVersion: 2.4`

---

changelog/fix_a_false_positive_for_performance_string_identifier_argument.md
lib/rubocop/cop/performance/string_identifier_argument.rb
spec/rubocop/cop/performance/string_identifier_argument_spec.rb

Fixes #289.
This PR fixes a false positive for `Performance/StringIdentifierArgument` when using namespaced class string argument.

[Fix #289] Fix a false positive for `Performance/StringIdentifierArgument`

---

CHANGELOG.md
changelog/fix_performance_mapcompact_autocorrect_causing_invalid_syntax.md
lib/rubocop/cop/performance/map_compact.rb
spec/rubocop/cop/performance/map_compact_spec.rb

This commit fixes the issue when `Performance/MapCompact` auto-correction
fails to detect the argument block of an assignment method so it deletes
the block ending (i.e. `end` or `}`) when `map { ... }.compact` is
multiline.
```ruby
object.new_collection = collection.map do |item|
end.compact
object.new_collection = collection.filter_map do |item|
```
```ruby
object.new_collection = collection.map do |item|
end.compact
object.new_collection = collection.filter_map do |item|
end
```
----
```
rubocop -V
1.28.2 (using Parser 3.1.2.0, rubocop-ast 1.18.0, running on ruby 3.0.1 x86_64-darwin20)
- rubocop-performance 1.14.0
```

Fix `Performance/MapCompact` autocorrect causing invalid syntax 

---

changelog/fix_a_false_positive_for_performance_regexp_match.md
lib/rubocop/cop/performance/regexp_match.rb
spec/rubocop/cop/performance/regexp_match_spec.rb

Follow up https://github.com/rubocop/rubocop-performance/pull/288#issuecomment-1148453972.
This PR fixes a false positive for `Performance/RegexpMatch` when `TargetRubyVersion: 2.3`.

Fix a false positive for `Performance/RegexpMatch`

---

changelog/fix_false_negative_for_performance_chain_array_allocation.md
lib/rubocop/cop/performance/chain_array_allocation.rb
spec/rubocop/cop/performance/chain_array_allocation_spec.rb

This PR fixes a false negative for `Performance/ChainArrayAllocation` when using `array.first(do_something).uniq`.

Fix a false negative for `Performance/ChainArrayAllocation` 

---

changelog/fix_a_false_negative_for_performance_string_identifier_argument.md
lib/rubocop/cop/performance/string_identifier_argument.rb

This PR fixes a false negative for `Performance/StringIdentifierArgument` when using `instance_variable_defined?`.
It was due to a typo. I checked other method names and it seems that there is no problem.

Fix a false negative for `Performance/StringIdentifierArgument`

---

changelog/change_support_autocorrection_on_redundantmatch.md
lib/rubocop/cop/performance/redundant_match.rb
spec/rubocop/cop/performance/redundant_match_spec.rb

I found the following pattern is treated as an offense but not autocorrected, so tried to support it.
```ruby
something if /regexp/.match(string)
something if /regexp/ =~ string
```

Support autocorrection on `Performance/RedundantMatch` when receiver is a Regexp literal

---

.circleci/config.yml

Follow up https://github.com/rubocop/rubocop-performance/commit/f2b1319f.

Use `cimg/ruby` instead of deprecated `circleci/ruby` image

---

changelog/new_support_numbered_parameter.md
lib/rubocop/cop/mixin/sort_block.rb
lib/rubocop/cop/performance/redundant_sort_block.rb
lib/rubocop/cop/performance/sort_reverse.rb
lib/rubocop/cop/performance/times_map.rb
spec/rubocop/cop/performance/redundant_sort_block_spec.rb
spec/rubocop/cop/performance/sort_reverse_spec.rb
spec/rubocop/cop/performance/times_map_spec.rb

This PR support numbered parameter for `Performance/RedundantSortBlock`, `Performance/SortReverse`, and `Performance/TimesMap` cops.

Support numbered parameter for `RedundantSortBlock`, `SortReverse`, and `TimesMap`

---

changelog/change_support_autocorrection_even_if_reject_is_used.md
lib/rubocop/cop/performance/count.rb
spec/rubocop/cop/performance/count_spec.rb

Until now, autocorrect was given up when reject was used, but it is now supported.
```ruby
array.reject { |e| e > 2 }.size
array.count { |e| !(e > 2) }
```
```ruby
array.reject { |e| e > 2 }.count
array.count { |e| !(e > 2) }
```
```ruby
array.reject { |e| e > 2 }.length
array.count { |e| !(e > 2) }
```
```ruby
array.reject(&:value).size
array.count { |element| !element.value }
```
```ruby
array.reject(&block).size
array.count { !block.call }
```
```ruby
array.reject {
foo
bar
}.length
array.count {
foo
!(bar)
}
```
The last one looks a bit weird but I think other cops autocorrects it to some other good form. If there is a better way to negate statements, I'd like to use it.
[1]: …

Support autocorrection even if `reject` is used on `Performance/Count`

---

changelog/fix_an_error_for_performance_map_compact.md
lib/rubocop/cop/performance/map_compact.rb
spec/rubocop/cop/performance/map_compact_spec.rb

Fixes #309.
This PR fixes an error for `Performance/MapCompact` when using `map(&:do_something).compact` and there is a line break after `map.compact` and assigning with `||=`.

[Fix #309] Fix an error for `Performance/MapCompact`

---

changelog/fix_regexp_match_to_handle_cbase_regexp.md
lib/rubocop/cop/performance/regexp_match.rb
spec/rubocop/cop/performance/regexp_match_spec.rb

Fix `Performance/RegexpMatch` to handle `::Regexp`

---

changelog/change_string_include_handle_not_match.md
lib/rubocop/cop/performance/string_include.rb
spec/rubocop/cop/performance/string_include_spec.rb

Extend `Performance/StringInclude` to handle `!~`

---

changelog/fix_a_false_negative_for_performance_redundant_string_chars.md
lib/rubocop/cop/performance/redundant_string_chars.rb
spec/rubocop/cop/performance/redundant_string_chars_spec.rb

Fixes #313.
This PR fixes a false negative for `Performance/RedundantStringChars` when using `str.chars.last` without argument.
Report #249 has `str.chars.last(2)` argument. #250 mistakenly changed even without arguments `str.chars.last`.

[Fix #313] Fix a false negative for `Performance/RedundantStringChars`

---

changelog/fix_a_false_positive_for_performance_sum.md
lib/rubocop/cop/performance/sum.rb
spec/rubocop/cop/performance/sum_spec.rb

This PR fixes a false positive for `Performance/Sum` when using `TargetRubyVersion` is 2.3 or lower.
Because `Array#sum` was introduced in Ruby 2.4.

Fix a false positive for `Performance/Sum`

---

lib/rubocop/cop/performance/detect.rb

In addition to the external library activerecord, the built in Hash class also has compatibility issues.
I'm unsure if this deserves a changelog entry, given it doesn't change the code there shouldn't be an impact (which is why I didn't add tests either).

[Fix #336] Expand the safety warning on Performance/Detect

---

changelog/change_register_offenses_for_variables_against.md
lib/rubocop/cop/performance/string_include.rb
spec/rubocop/cop/performance/string_include_spec.rb

See https://github.com/rails/rails/pull/46910.
The second pattern of `StringInclude#redundant_regex?`(`(send (regexp (str $#literal?) (regopt)) {:match :match?} $str)`) is pretty useless, because it only detects cases like `'str'.match?(/str/)`, so literal regex is matched against literal string. But does anyone write such code?
That pattern was implemented that way, because, to avoid cases when the receiver is a symbol and symbol does not implement `#include?`. But, it already marks as offense and autocorrects `can_be_a_symbol.match?(/abc/)`! So I think this PR changes are fair.

Register offenses for variables against regexes in `Performance/StringInclude`

---

changelog/change_redundant_equality_comparison_block_additional_regexp_methods.md
lib/rubocop/cop/performance/redundant_equality_comparison_block.rb
spec/rubocop/cop/performance/redundant_equality_comparison_block_spec.rb

Closes #339.
`Regexp#match` technically can be added too, but this can produce more false positives due to its name popularity 🤔

Enhance `RedundantEqualityComparisonBlock` to check `=~` and `match?` methods

---

lib/rubocop/cop/performance/detect.rb

Since this cop tries to use `Array#reverse`, it would be better to explain that it depends on `Array`, not `Enumerable`. And I also thought that ActiveRecord (`ActiveRecord::Relation` to be exact) part should be removed from the description since there is no problem (anymore?).
Also see the comments on:
- https://github.com/rubocop/rubocop-performance/pull/337

Improve safety section on `Performance/Detect`

---

changelog/fix_flat_map_autocorrect_separate_lines.md
lib/rubocop/cop/performance/flat_map.rb
spec/rubocop/cop/performance/flat_map_spec.rb

Fixes https://github.com/rubocop/rubocop-performance/issues/344.

Fix `FlatMap` autocorrection for chained methods on separate lines

---

changelog/fix_a_false_positive_for_performance_string_identifier_argument.md
lib/rubocop/cop/performance/string_identifier_argument.rb
spec/rubocop/cop/performance/string_identifier_argument_spec.rb

Fixes #346.
This PR fixes a false positive for `Performance/StringIdentifierArgument` when using a command method with receiver. It makes that cop to allow some command methods that don't normally specify a receiver.

[Fix #346] Fix a false positive for `Performance/StringIdentifierArgument`

---

changelog/fix_default_config_of_redundant_equality_comparison_block.md
config/default.yml
lib/rubocop/cop/performance/redundant_equality_comparison_block.rb

This PR fixes `AllowRegexpMatch` of `Performance/RedundantEqualityComparisonBlock` by default.
Default value is true as documented example below:
https://docs.rubocop.org/rubocop-performance/cops_performance.html#performanceredundantequalitycomparisonblock

Fix `AllowRegexpMatch` of `Performance/RedundantEqualityComparisonBlock` by default

---

.circleci/config.yml
.rubocop.yml
changelog/change_drop_ruby_2_6_support.md
rubocop-performance.gemspec
spec/project_spec.rb
tasks/changelog.rb

Follow up https://github.com/rubocop/rubocop/pull/11791.
This PR drops Ruby 2.6 support. And JRuby has been dropped from the CI matrix because no JRuby-specific issues have been found and prevents the following build error:
```console
#!/bin/bash -eo pipefail
bundle install
Fetching https://github.com/rubocop/rubocop.git
You need to install git to be able to use gems from git repositories. For help
installing git, please refer to GitHub's tutorial at
https://help.github.com/articles/set-up-git
Exited with code exit status 11
CircleCI received exit code 11
```
https://app.circleci.com/pipelines/github/rubocop/rubocop-minitest/926/workflows/68776b54-5856-4acd-a99a-f41df114634d/jobs/6034
This does not mean no support for JRuby. RuboCop Performance will continue to support JRuby 9.4+. …

Drop Ruby 2.6 support

---

changelog/fix_autocorrect_constant_regexp_and_regexp_match.md
lib/rubocop/cop/performance/constant_regexp.rb
lib/rubocop/cop/performance/regexp_match.rb
spec/rubocop/cli/autocorrect_spec.rb

Fix an incorrect autocorrect for `Performance/ConstantRegexp` and `Performance/RegexpMatch` when autocorrecting both at the same time

---

changelog/change_compare_with_block_methods.md
lib/rubocop/cop/performance/compare_with_block.rb
spec/rubocop/cop/performance/compare_with_block_spec.rb

`Performance/CompareWithBlock` currently only looks at `sort`, `min` and `max` usage.
This PR adds support for `sort!` and `minmax` methods which behave the same way.
```ruby
arr.minmax { |a, b| a.foo <=> b.foo }
arr.sort!  { |a, b| a.foo <=> b.foo }
arr.minmax_by(&:foo)
arr.sort_by!(&:foo)
```
```
Comparison:
minmax_by:  1513625.0 i/s
minmax:     1178249.9 i/s - 1.28x  slower
```
```
Comparison:
sort_by!:    21368.8 i/s
sort!:       13662.7 i/s - 1.56x  slower
```

Add `sort!` and `minmax` to `Performance/CompareWithBlock`

---

changelog/fix_a_false_positive_for_performance_redundant_equality_comparison_block.md
lib/rubocop/cop/performance/redundant_equality_comparison_block.rb
spec/rubocop/cop/performance/redundant_equality_comparison_block_spec.rb

Fixes #359.
This PR fixes a false positive for `Performance/RedundantEqualityComparisonBlock` when the block variable is used on both sides of `==`.

[Fix #359] Fix a false positive for `Performance/RedundantEqualityComparisonBlock`

---

changelog/fix_false_positives_for_performance_array_semi_infinite_range_slice.md
lib/rubocop/cop/performance/array_semi_infinite_range_slice.rb
spec/rubocop/cop/performance/array_semi_infinite_range_slice_spec.rb

Fixes #365.
This PR fixes false positives for `Performance/ArraySemiInfiniteRangeSlice` when using `[]` with string literals.
What this can do is accept string literals, as they are already marked as unsafe.

[Fix #365] Fix false positives for `Performance/ArraySemiInfiniteRangeSlice`

---

changelog/fix_an_incorrect_autocorrect_for_performance_block_given_with_explicit_block.md
lib/rubocop-performance.rb
lib/rubocop/cop/performance/block_given_with_explicit_block.rb
spec/rubocop/cli/autocorrect_spec.rb

Fixes #367.
This PR fixes an incorrect autocorrect for `Performance/BlockGivenWithExplicitBlock` when using `Lint/UnusedMethodArgument`'s autocorrection together.

[Fix #367] Fix an incorrect autocorrect for `Performance/BlockGivenWithExplicitBlock`

---

changelog/fix_an_incorrect_autocorrect_for_performance_redundant_match.md
lib/rubocop/cop/performance/redundant_match.rb
spec/rubocop/cop/performance/redundant_match_spec.rb

Fixes #370.
This PR fixes an incorrect autocorrect for `Performance/RedundantMatch` when expressions with lower precedence than `=~` are used as an argument.

[Fix #370] Fix an incorrect autocorrect for `Performance/RedundantMatch`

---

changelog/fix_target_version_for_unfreeze_string_cop.md
lib/rubocop/cop/performance/unfreeze_string.rb
spec/rubocop/cop/performance/unfreeze_string_spec.rb

As stated in the class documentation, unary plus operator is available from Ruby 2.3.
This fix prevent RuboCop Performance to raise an offense when configured to support Ruby 2.2

Set target version for `Performance/UnfreezeString`

---

changelog/fix_an_error_for_performance_map_method_chain.md
lib/rubocop/cop/performance/map_method_chain.rb
spec/rubocop/cop/performance/map_method_chain_spec.rb

Fixes #374.
This PR fixes an error for `Performance/MapMethodChain` when using `map` method chain without receiver.

[Fix #374] Fix an error for `Performance/MapMethodChain`

---

lib/rubocop/cop/performance/count.rb

This pull request improves the doc for `Performance/Count` .
- Removed almost duplicate sentences (left the latter one only):
> ActiveRecord's `count` ignores the block that is passed to it.
> `ActiveRecord` will ignore the block that is passed to `count`.
- Added Rails version that fixed the described `count` method issue. Since it has been fixed in 2016, newer Rails users will not encounter this issue. 
> Fixed ActiveRecord::Relation#count to use Ruby's Enumerable#count for counting records when a block is passed as argument instead of silently ignoring the passed block. ([Pull Request](https://github.com/rails/rails/pull/24203))
- <https://guides.rubyonrails.org/5_1_release_notes.html>
[1]: …

Update the doc for `Performance/Count`

---

changelog/change_require_rubocop_ast_1_30.md
lib/rubocop/cop/performance/inefficient_hash_search.rb
lib/rubocop/cop/performance/redundant_equality_comparison_block.rb
lib/rubocop/cop/performance/reverse_first.rb
rubocop-performance.gemspec

Follow up https://github.com/rubocop/rubocop/pull/12305.

Require RuboCop AST 1.30.0+

---

config/default.yml
docs/modules/ROOT/pages/cops_performance.adoc

1) Follow by https://github.com/fastruby/fast-ruby/pull/222
2) I've replaced invalid links with valid ones.

Revise links

---

changelog/fix_a_false_negative_for_string_identifier_argument.md
lib/rubocop/cop/performance/string_identifier_argument.rb
spec/rubocop/cop/performance/string_identifier_argument_spec.rb

Closes #386, see there for benchmark script. The improvement isn't quite as large as for the other cases of this cop but it's still measurable. In addition it makes the code more uniform.

Make `Performance/StringIdentifierArgument` aware of string interpolation

---

.github/workflows/test.yml
changelog/change_require_rubocop_1_33_as_a_runtime_dependency.md
lib/rubocop/cop/performance/redundant_merge.rb
rubocop-performance.gemspec

This PR makes RuboCop Performance require RuboCop 1.30+ to fix some errors:
https://github.com/rubocop/rubocop-performance/actions/runs/6966652446/job/18957154150
It introduces CI for the oldest RuboCop version still supported, implementing a workflow for regression testing that is similar to the one found a https://github.com/rubocop/rubocop-rails/commit/c9acb7a.

Require RuboCop 1.30+ as runtime dependency

---

changelog/change_improve_performance_map_compact_to.md
lib/rubocop/cop/performance/map_compact.rb
spec/rubocop/cop/performance/map_compact_spec.rb

Fixes https://github.com/rubocop/rubocop-performance/issues/389.

Improve `Performance/MapCompact` to handle more safe navigation calls

---

changelog/fix_false_negative_for_reverse_each.md
lib/rubocop/cop/performance/reverse_each.rb
spec/rubocop/cop/performance/reverse_each_spec.rb

Fixes https://github.com/rubocop/rubocop-performance/issues/390.

Fix a false negative for `Performance/ReverseEach` when safe navigation is between `reverse` and `each`

---

changelog/fix_make_performance_sum_aware_of_safe_navigation_operator.md
lib/rubocop/cop/performance/sum.rb
spec/rubocop/cop/performance/sum_spec.rb

Fixes #401.
This PR makes `Performance/Sum` aware of safe navigation operator.

[Fix #401] Make `Performance/Sum` aware of safe navigation operator

---

lib/rubocop/cop/performance/times_map.rb
spec/rubocop/cop/performance/times_map_spec.rb

Fixes #421.
This PR fixes false positives for `Performance/TimesMap` with a block with safe navigation call for nil literal.
It does not have a changelog entry because it is a patch to a feature that has not been released yet.

[Fix #421] Fix false positives for `Performance/TimesMap`

---

changelog/fix_false_negatives_for_performance_string_identifier_argument.md
lib/rubocop/cop/performance/string_identifier_argument.rb
spec/rubocop/cop/performance/string_identifier_argument_spec.rb

This PR fixes false negatives for `Performance/StringIdentifierArgument` when using multiple string arguments.
e.g., `alias_method 'new', 'original'`

Fix false negatives for `Performance/StringIdentifierArgument`

---

changelog/fix_false_positive_for_string_identifier_argument.md
lib/rubocop/cop/performance/string_identifier_argument.rb
spec/rubocop/cop/performance/string_identifier_argument_spec.rb

As per my findings in https://github.com/rubocop/rubocop-performance/pull/427#issuecomment-1865914939
I updated docs with string interpolation with an explicit example. It's not quite like the initial issue report where the colon came from the variable but it should get the point across.

[Fix #425] Fix a false positive for`Performance/StringIdentifierArgument

---

changelog/fix_a_false_positive_for_performance_chain_array_allocation.md
lib/rubocop/cop/performance/chain_array_allocation.rb
spec/rubocop/cop/performance/chain_array_allocation_spec.rb

Fixes #437.
This PR fixes a false positive for `Performance/ChainArrayAllocation` when using `select` with block argument after `select`.

[Fix #437] Fix a false positive for `Performance/ChainArrayAllocation`

---

changelog/change_disalbe_performance_casecmp_by_default.md
config/default.yml
lib/rubocop/cop/performance/casecmp.rb

This cop suggests an incorrect fix when code involves non-ASCII characters. Disabling it by default makes this risky behavior opt-in rather than opt-out.

[Fix #240] Disable `Performance/Casecmp` cop

---

.github/workflows/test.yml
Gemfile
Rakefile
changelog/new_support_prism.md
lib/rubocop/cop/performance/end_with.rb
lib/rubocop/cop/performance/start_with.rb
lib/rubocop/cop/performance/string_include.rb
rubocop-performance.gemspec
spec/rubocop/cop/performance/bind_call_spec.rb
spec/rubocop/cop/performance/collection_literal_in_loop_spec.rb
spec/rubocop/cop/performance/delete_prefix_spec.rb
spec/rubocop/cop/performance/delete_suffix_spec.rb
spec/rubocop/cop/performance/map_compact_spec.rb
spec/rubocop/cop/performance/redundant_equality_comparison_block_spec.rb
spec/rubocop/cop/performance/redundant_merge_spec.rb
spec/rubocop/cop/performance/regexp_match_spec.rb
spec/rubocop/cop/performance/select_map_spec.rb
spec/rubocop/cop/performance/string_identifier_argument_spec.rb
spec/rubocop/cop/performance/sum_spec.rb
spec/rubocop/cop/performance/unfreeze_string_spec.rb
spec/spec_helper.rb

Follow up https://github.com/rubocop/rubocop-ast/pull/277
In Prism (`Prism::Translation::Parser`), `match-with-lvasgn` can be distinctly differentiated.
It is unclear whether to conform to the current behavior of the Parser gem, but initially, `def_node_matcher` has been updated to accept the following incompatibilities for `Performance/EndWith`, `Performance/StringInclude`, and `Performance/StartWith` cops to ensure it works with Prism 0.24.0 as well.
Returns an `match_with_lvasgn` node:
```console
$ bundle exec ruby -rparser/ruby33 -ve 'p Parser::Ruby33.parse("/foo/ =~ bar")'
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-darwin22]
s(:match_with_lvasgn,
s(:regexp,
s(:str, "foo"),
s(:regopt)),
s(:send, nil, :bar))
```
Returns an `match_with_lvasgn` node:
```console
$ bundle exec …
```

Support Prism as a Ruby parser

---

changelog/fix_false_positive_for_performance_redundant_block_call.md
lib/rubocop/cop/performance/redundant_block_call.rb
spec/rubocop/cop/performance/redundant_block_call_spec.rb

Fixes #448.
This PR fixes a false positive for `Performance/RedundantBlockCall` when using `block.call` with block argument.

[Fix #448] Fix a false positive for `Performance/RedundantBlockCall`

---

lib/rubocop/cop/performance/map_compact.rb

When I first read about the [`Performance/MapCompact`](https://docs.rubocop.org/rubocop-performance/cops_performance.html#safety-11) cop, I didn't understand the following sentence at first glance:
> This cop's autocorrection is unsafe because `map { ... }.compact` that is not compatible with `filter_map`.
- The `that` in this sentence is confusing me grammatically-wise.
- And this explanation did not hint me to _why_ it's not safe. In hindsight, I don't know why I haven't just looked at the example one line above to see the actual difference. But maybe, for other users, it might be as well beneficial to improve the wording and refer to the given example to clearly point out that falsy values are filtered out by `filter_map` as well (see the [Ruby …

Improve explanation for safety of `MapCompact` autocorrection in docs

---

spec/rubocop/cop/performance/collection_literal_in_loop_spec.rb
spec/rubocop/cop/performance/redundant_merge_spec.rb
spec/rubocop/cop/performance/string_identifier_argument_spec.rb

This PR restores skipped specs for Prism. They have already been resolved in Prism, so they can be tested.

Restore skipped specs for Prism

---

changelog/fix_error_for_redundant_equality_comparison_block.md
lib/rubocop/cop/performance/redundant_equality_comparison_block.rb
spec/rubocop/cop/performance/redundant_equality_comparison_block_spec.rb

Fix error for `Performance/RedundantEqualityComparisonBlock` when block is empty

---

spec/project_spec.rb

Also update cop filtering for https://github.com/rubocop/rubocop/pull/13123

Don't use deprecated `Cop.registry` in specs

---

spec/rubocop/cli/autocorrect_spec.rb
spec/rubocop/cop/performance/sum_spec.rb

The skipped tests fail with the following command: `bundle exec rspec ./spec/rubocop/cli/autocorrect_spec.rb[1:1] ./spec/rubocop/cop/performance/sum_spec.rb[1:13] --seed 26805` (or maybe not, there is something extra going on I don't understand)
This is fine to do in the rubocop main repository but here we inject additional config values that are not restored.
There are some things going on that I don't entirely understand:
* Why only failures in this one file
* Why did koic not manage to reproduce with the exact same seed
* Why did the failures seemingly disappear and reappear without any changes to the code
But regardless, this is more correct. Removing the JRuby skips is a bit of a guess on my side but I don't see what else should prevent them from passing. Let's see how it goes.
Bit …

Fix a random test failure for `Performance/Sum`

---

lib/rubocop/cop/performance/redundant_merge.rb

Minimum version is currently 1.48

Remove RuboCop < 1.44 workaround

---

lib/rubocop/cop/performance/big_decimal_with_numeric_argument.rb
spec/rubocop/cop/performance/big_decimal_with_numeric_argument_spec.rb

Fixes #454.
This PR fixes false positives for `Performance/BigDecimalWithNumericArgument` when using BigDecimal 3.1+.
The bad and good examples for this cop are reversed between BigDecimal 3.0 and 3.1.
Since BigDecimal 3.1 is the default gem in Ruby 3.1, this PR reverses the bad and good examples when targeting Ruby 3.1+. So, the goal of this PR is to address many cases where the meaning was entirely reversed.
To avoid introducing excessive complexity related to version dependencies, detection is disabled for Ruby 3.0 and below.
Ideally, a solution that prioritizes the BigDecimal version would be best in the future, but this PR does not take that into account.

[Fix #454] Fix false positives for `Performance/BigDecimalWithNumericArgument`

---

changelog/change_disable_block_given.md
config/default.yml
lib/rubocop/cop/performance/block_given_with_explicit_block.rb

See linked issue for benchmark details.
I tested with YJIT and its even worse:
```
ruby 3.4.0dev (2024-09-05T09:43:46Z master 63cbe3f6ac) +YJIT [x86_64-linux]
block     1.635M i/100ms
block w/ block   285.930k i/100ms
block_given?     1.867M i/100ms
block_given? w/ block
1.497M i/100ms
Calculating -------------------------------------
block     22.611M (±12.7%) i/s   (44.23 ns/i) -    111.180M in   5.033721s
block w/ block      3.034M (± 8.5%) i/s  (329.59 ns/i) -     15.154M in   5.032609s
block_given?     24.935M (±10.7%) i/s   (40.10 ns/i) -    123.254M in   5.002983s
block_given? w/ block
23.007M (±14.7%) i/s   (43.47 ns/i) -    113.782M in   5.058213s
Comparison:
block_given?: 24935388.3 i/s
block_given? w/ block: 23006920.5 i/s - …
```

[Fix #385] Disable `Performance/BlockGivenWithExplicitBlock` by default

---

changelog/change_make_double_start_end_aware_safe_navigation.md
lib/rubocop/cop/performance/double_start_end_with.rb
spec/rubocop/cop/performance/double_start_end_with_spec.rb

Fixes #407.
In case of inconsistent safe navigation, it keeps the dot from the first receiver.
This shouldn't change anything:
Depending on the order, it was either not needed or it will continue raising.
`Lint/SafeNavigationConsistency` takes care of this anyways

Fix [#407] Make `Performance/DoubleStartEndWith` aware of safe navigation

---

changelog/fix_false_positives_for_performance_big_decimal_with_numeric_argument.md
lib/rubocop/cop/performance/big_decimal_with_numeric_argument.rb
spec/rubocop/cop/performance/big_decimal_with_numeric_argument_spec.rb

Fixes #468.
This PR fixes false positives for `Performance/BigDecimalWithNumericArgument` when using float argument for `BigDecimal`.
In Ruby 3.1 and later, cases where numbers are faster than strings are limited to `Integer`. For `Float`, strings are still faster:
```console
$ cat example.rb
require 'benchmark/ips'
require 'bigdecimal'
require 'bigdecimal/util'
x.report('float string')             { BigDecimal('4.2') }
x.report('float with prec')          { BigDecimal(4.2, Float::DIG + 1) }
x.report('to_d string without prec') { '4.2'.to_d }
x.report('to_d float without prec')  { 4.2.to_d }
x.report('to_d float with prec')     { 4.2.to_d(Float::DIG + 1) }
x.compare!
end
```
```console
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-darwin22]
Warming up …
```

[Fix #468] Fix false positives for `Performance/BigDecimalWithNumericArgument`

---

changelog/fix_performance_redundant_string_chars_cop_error_in_case_of_implicit_receiver.md
lib/rubocop/cop/performance/redundant_string_chars.rb
spec/rubocop/cop/performance/redundant_string_chars_spec.rb

```console
echo 'chars.size' | be rubocop --only Performance/RedundantStringChars --stdin bug.rb -d
Scanning bug.rb
An error occurred while Performance/RedundantStringChars cop was inspecting bug.rb:1:0.
undefined method `begin_pos' for nil
lib/rubocop/cop/performance/redundant_string_chars.rb:76:in `correction_range'
lib/rubocop/cop/performance/redundant_string_chars.rb:62:in `block in on_send'
```

Fix `Performance/RedundantStringChars` cop error in case of implicit receiver

---

lib/rubocop/cop/performance/count.rb

[DOC] Fix markup of `Performance/Count`

---

changelog/fix_performance_squeeze_cop_error_on_frozen_ast_string_node_value.md
lib/rubocop/cop/performance/squeeze.rb
spec/rubocop/cop/performance/squeeze_spec.rb

Since sometimes AST string nodes might have their values frozen, we should call `dup` explicitly to make sure `to_string_literal` (which does not work with frozen strings) does not raise. Maybe we should also apply a patch on RuboCop's core side to fix the `to_string_literal` itself (it now uses `force_encoding` on its argument).
See [1] and [2] for details.
[1] https://github.com/ruby/prism/issues/3309
[2] https://github.com/rubocop/rubocop-ast/issues/342

Fix `Performance/Squeeze` cop error on frozen AST string node value

---

lib/rubocop/cop/performance/chain_array_allocation.rb
lib/rubocop/cop/performance/collection_literal_in_loop.rb

For these, it is known on what methods they will operate on

Add missing `RESTRICT_ON_SEND` for two cops

---

lib/rubocop/cop/performance/array_semi_infinite_range_slice.rb
lib/rubocop/cop/performance/range_include.rb

`rubocop-ast` defines some node groups (https://github.com/rubocop/rubocop-ast/blob/85bfe84/lib/rubocop/ast/node.rb#L89-L116) that can be used in place of a union of node types.

Use node groups in node patterns to replace unions of types

---

changelog/change_collection_literal_include_ruby34.md
lib/rubocop/cop/performance/collection_literal_in_loop.rb
spec/rubocop/cop/performance/collection_literal_in_loop_spec.rb

Fix #482. Since `include?` on arrays are the only instances I ever run across this cop, I think it makes sense to add special handling for this.
On Ruby 3.4 this does no array allocations:
```rb
require "memory_profiler"
class Foo
def bar
Bar.new
end
end
class Bar
def baz
end
end
foo = Foo.new
report = MemoryProfiler.report do
[1,2].include?(foo.bar.baz)
end.pretty_print
```
Also, this code is simply slower on Ruby 3.4:
```rb
require "benchmark/ips"
local = [301, 302]
val = 301
x.report('local') do
local.include?(val)
end
x.report('literal') do
[301, 302].include?(val)
end
x.compare!
end
```
```
$ ruby test.rb
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [x86_64-linux]
local     1.822M i/100ms
literal     2.296M …
```

Change `Performance/CollectionLiteralInLoop` to not register offenses for `Array#include?` that are optimized directly in Ruby.

---

changelog/fix_false_positives_for_performance_string_identifier_argument.md
lib/rubocop/cop/performance/string_identifier_argument.rb
spec/rubocop/cop/performance/string_identifier_argument_spec.rb

This PR fixes false positives for `Performance/StringIdentifierArgument` when using interpolated string argument.
Converting a string with interpolation into a symbol degrades performance.
Fixes #492.

[Fix #492] Fix false positives for `Performance/StringIdentifierArgument`

---

changelog/fix_fix_performance_fixed_size_false.md
lib/rubocop/cop/performance/fixed_size.rb
spec/rubocop/cop/performance/fixed_size_spec.rb

Fixes https://github.com/standardrb/standard/issues/702.

Fix `Performance/FixedSize` false positive when `count` is called with a `numblock`

---

.github/workflows/test.yml
changelog/new_support_itblock_in_performance_cops.md
lib/rubocop/cop/performance/times_map.rb
lib/rubocop/cop/performance/zip_without_block.rb
rubocop-performance.gemspec
spec/rubocop/cop/performance/chain_array_allocation_spec.rb
spec/rubocop/cop/performance/redundant_block_call_spec.rb
spec/rubocop/cop/performance/times_map_spec.rb
spec/rubocop/cop/performance/zip_without_block_spec.rb
spec/spec_helper.rb

This PR supports `it` block parameter in `Performance` cops.

Support `it` block parameter in `Performance` cops

---

changelog/fix_performance_count_cop_error_on_empty_selector_block.md
lib/rubocop/cop/performance/count.rb
spec/rubocop/cop/performance/count_spec.rb

Something like
```ruby
collection.reject { }.size
```
would lead to an error

Fix `Performance/Count` cop error on empty selector block

---

changelog/fix_mark_performance_map_compact_cop_as.md
config/default.yml
lib/rubocop/cop/performance/map_compact.rb

**Replace this text with a summary of the changes in your PR.
`Performance/MapCompact` is marked as safe but it should not be as the suggested refactoring is not equivalent
```ruby
[true, false, nil].compact              #=> [true, false]
[true, false, nil].filter_map(&:itself) #=> [true]
```
This is confusing for new Ruby developers.

[Fix #500] Mark `Performance/MapCompact` cop as unsafe

---

config/default.yml

```
$ bundle exec rake references:verify
ERROR: https://twitter.com/schneems/status/1034123879978029057 (302)
ERROR: https://docs.gitlab.com/ee/development/performance.html#reading-from-files-and-other-data-sources (301)
```
Twitter 302 is due to domain change, but the tweat actually does not exist anymore (see https://x.com/schneems/status/1034123879978029057)

Actualize references

---

changelog/fix_performance_count_multiline_error.md
lib/rubocop/cop/performance/count.rb
spec/rubocop/cop/performance/count_spec.rb

Currently, `Performance/Count` will autocorrect:
```ruby
foo
.select(&:something)
.count
.positive?
```
to:
```ruby
foo
.count(&:something)
.positive?
```
which is not valid syntax. This PR fixes autocorrection to:
```ruby
foo
.count(&:something)
.positive?
```

Fix autocorrection syntax error for `Performance/Count` with multiline calls

---

changelog/fix_false_positives_for_performance_redundant_string_chars.md
lib/rubocop/cop/performance/redundant_string_chars.rb
spec/rubocop/cop/performance/redundant_string_chars_spec.rb

Fix false positives for `Performance/RedundantStringChars` when using `str.chars[0, 2]`.
Fixes #517.

[Fix #517] Fix false positives for `Performance/RedundantStringChars`
